### ISSUE TITLE
Remove fs.readFileSync calls?

### ISSUE THREAD

**Issue by phated** [gulpjs/vinyl-sourcemap#1]
When the error-first-callback idea was discussed, I thought that the `fs.readFileSync` calls would be replaced with their async counterpart.  Do you think that would be possible or does it add too much complexity?

**Comment by phated** [comment]
Was also hoping to reduce/remove the `try/catch` calls.

**Comment by robvenn** [comment]
This would be better indeed. 
It's definitely feasible but it gets more complex to reason about with all the nested `if` blocks. 
Perhaps it could be improved with some third party library like async, otherwise just need to split up the logic into multiple functions that have to be called at the right time.

**Comment by robvenn** [comment]
Working on this... got the `add` method updated with async `readFile`. 
I'll look at the other one next. I've removed the `addSync` and `writeSync` methods as well.

**Comment by robvenn** [comment]
Ok so I've replaced the remaining `readFileSync` method as well... this also reduces the try/catch blocks, will open PR for review or can I just merge it myself?

**Comment by phated** [comment]
Closed by #7
