### ISSUE TITLE
Attempt to remove as many options as possible

### ISSUE THREAD

**Issue by phated** [gulpjs/vinyl-sourcemap#19]
A goal of mine is to gut as many options as we possibly can.  We should be able to figure out the right way to do things in __many__ cases, so users shouldn't have to use things like `mapFile` or `mapSources`, etc.

I'm not sure exactly which options can be removed but we need to have a deep understanding why people are using it and how we can do that automatically before we can remove an option.

**Comment by phated** [comment]
Creating modules as option replacements at https://github.com/gulp-sourcemaps.  If anyone wants to help, I'll give you access to the repo.

**Comment by phated** [comment]
cc @robinvenneman @contra @AlexHenkel or anyone else

**Comment by CKGrafico** [comment]
Do you have a list with all options?
options.sourceRoot
options.loadMaps // load loadInlineMaps

**Comment by phated** [comment]
@CKGrafico https://github.com/gulp-sourcemaps/gulp-sourcemaps#init-options and https://github.com/gulp-sourcemaps/gulp-sourcemaps#write-options

**Comment by CKGrafico** [comment]
My opinions about that are only based on my experiences with sourcemaps:
- loadMaps: I don't use this because I try to use always JS code without min (also with 3rd party) and I'm who minifies the code.
- identityMap: Never need that
- addComment: Not for me but I understand that some people need it.
- includeContent: For me is always true.
- sourceRoot: if the last is true I don't need it.
- destPath: I prefer inline sourcemaps but maybe someone not.
- sourceMappingURLPrefix: Only needed is you don't use inline.
- sourceMappingURL: The same.
- mapFile: The same.
- charset: Mmm never for me but not sure if someone has code without utf-8
- clone: Never used but could be insteresting.

**Comment by Videl** [comment]
@phated, do you have a list of what options needs to be implemented?

**Comment by phated** [comment]
@Videl Almost all the options listed in the comment above yours.  I started creating repositories for each at https://github.com/gulp-sourcemaps/ and worked on `addComment`/`sourceMappingURLPrefix`/`sourceMappingURL` (in an open PR) and `mapSources`.  `charset` doesn't need to be replaced and `clone` might not need to be (needs to be researched).

**Comment by phated** [comment]
`identityMap` has been removed because I finished https://github.com/gulp-sourcemaps/identity-map today.

**Comment by phated** [comment]
I just chopped out everything.  Will have to create plugins as they are needed but creating them as I tried to remove options was just slowing progress.
