### ISSUE TITLE
Should an error occur in .write if no sourceMap on file?

### ISSUE THREAD

**Issue by phated** [gulpjs/vinyl-sourcemap#5]
I'm not sure it's appropriate to surface an error if a the `sourceMap` property is missing from a `file`.  Maybe it should just callback successfully (similar to the case of non-Buffer contents).

**Comment by robvenn** [comment]
Hmm, if I remember correctly the way that I did this was check if there was a sourcemap in the gulp-sourcemaps code and only call vinyl-sourcemap if needed... otherwise it would throw an error. But your suggestion might be better, I'm not sure either.

Either way the `!file.sourceMap` check with error or success callback should also come before everything else then.

**Comment by phated** [comment]
That would be fine for gulp-sourcemaps but we are going to be using this module directly in vinyl-fs so we should definitely check that the property exists instead of throwing an error.

**Comment by phated** [comment]
Turns out that gulp-sourcemap (recent change?) just pushes the file along if the property doesn't exist so this change makes sense for us.
